apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-dir
  namespace: jhub
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvr0"
    path: "gvr0/jupyterhub/hub-db-dir"
    readOnly: false
