apiVersion: v1
kind: PersistentVolume
metadata:
  name: claim-supermap
  namespace: jhub
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvr0"
    path: "gvr0/jupyterhub/claim-supermap"
    readOnly: false
